base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from main.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("", include("main.urls", namespace="main")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "blog"

urlpatterns = [
    path("", PostList.as_view(), name="home"),
    path("about/", TemplateView.as_view(template_name="blog/about.html"), name="about"),
    path(
        "contact/",
        TemplateView.as_view(
            template_name="blog/contact.html",
            extra_context={"work": "Разработка программного обеспечения"},
        ),
        name="contact",
    ),
    path("single_post/", SinglPostList.as_view(), name="single_post"),
    path("left_post/", LeftSinglPostList.as_view(), name="left_post"),
    path("three_post/", ThreePostList.as_view(), name="three_post"),
    path("gallery_post/", GalleryPostList.as_view(), name="gallery_post"),
    path("<str:slug>/", PostDetailView.as_view(), name="post"),
    path("rubric/<int:pk>/", ArticleByCategoryListView.as_view(), name="rubric"),
    # path("category/<int:pk>/", GalleryByCategoryListView.as_view(), name="category"),
    path("category/<int:pk>/", get_category, name="category"),
]

main/urls.py
from django.urls import path

from .views import *

app_name = "main"

urlpatterns = [
    path("", index, name="general"),
]

blog/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.urls import reverse


class Rubric(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:rubric", kwargs={"pk": self.pk})

    class MPTTMeta:
        order_insertion_by = ["name"]


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, verbose_name="Url", unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"id": self.id})

    class Meta:
        verbose_name = "Категория(ю)"
        verbose_name_plural = "Категории"
        ordering = ["title"]


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, verbose_name="Url", unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("tag", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"
        ordering = ["title"]


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, verbose_name="Url", unique=True)
    author = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Опубликовано")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True)
    views = models.IntegerField(default=0, verbose_name="Кол-во просмотров")
    category = TreeForeignKey(Rubric, on_delete=models.PROTECT)
    # category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='posts')
    tags = models.ManyToManyField(Tag, blank=True, related_name="posts")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Статья(ю)"
        verbose_name_plural = "Статьи"
        ordering = ["-created_at"]


# Загрузка изображений и видео (Gallery)


class Image(models.Model):
    title = models.CharField(
        max_length=100, null=False, verbose_name="Описание изображения"
    )
    image = models.ImageField(
        upload_to="image", verbose_name="Файл с изображением", null=True, blank=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, null=True, blank=True
    )

    obj_img = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:category", kwargs={"id": self.id})


class VideoFile(models.Model):
    title = models.CharField(max_length=100, null=False, verbose_name="Описание файла")
    file = models.FileField(
        upload_to="videos", verbose_name="Видеофайл", null=True, blank=True
    )
    obj_video = models.Manager()

    def __str__(self):
        return self.title

main/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Post, Rubric, Category, Image


class SinglPostList(ListView):
    model = Post
    template_name = "blog/single_post.html"
    context_object_name = "posts"
    paginate_by = 3


class LeftSinglPostList(ListView):
    model = Post
    template_name = "blog/left_single_post.html"
    context_object_name = "posts"
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(id__in=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


class ThreePostList(ListView):
    model = Post
    template_name = "blog/three_post.html"
    context_object_name = "posts"
    paginate_by = 9

    def get_queryset(self):
        return Post.objects.filter(id__in=[4, 7, 8, 9, 10, 13, 14, 15, 16])


class GalleryPostList(ListView):
    model = Post
    template_name = "blog/gallery_post.html"
    context_object_name = "posts"
    # paginate_by = 9


# def single_post(request):
#     posts = Post.objects.all()
#     return render(request, "blog/single_post.html", {"posts": posts})


# def left_single_post(request):
#     posts = Post.objects.all()
#     return render(request, "blog/left_single_post.html", {"posts": posts})


# def three_post(request):
#     posts = Post.objects.all()
#     return render(request, "blog/three_post.html", {"posts": posts})


class PostList(ListView):
    model = Post
    paginate_by = 3


class PostDetailView(DetailView):
    model = Post


def get_category(request, pk):
    posts = Post.objects.filter(category__pk=pk)
    return render(request, "blog/gallery_post.html", {"posts": posts})


class ArticleByCategoryListView(ListView):
    model = Post
    template_name = "blog/single_post.html"
    # template_name = 'blog/Post_by_category.html'
    context_object_name = "posts"
    paginate_by = 3
    category = None

    def get_queryset(self):
        self.category = Rubric.objects.get(pk=self.kwargs["pk"])
        queryset = Post.objects.all().filter(category__pk=self.category.pk)
        return queryset


# class GalleryByCategoryListView(ListView):
#     model = Post
#     template_name = "blog/gallery_post.html"
#     context_object_name = "post"
#     category = None

#     def get_queryset(self):
#         self.category = Category.objects.get(pk=self.kwargs["pk"])
#         queryset = Post.objects.all().filter(category__pk=self.category.pk)
#         return queryset
# return Post.objects.filter(category__pk=self.kwargs['pk'])

# def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['rubric'] = self.get_upper(Category.objects.get(pk=self.kwargs['pk']))
#         return context

main/views.py
from django.shortcuts import render

from blog.models import Post


def index(request):
    return render(request, "main/index.html")

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
	{% block content %}
	<div class="container">

		{% include 'blog/sidebar.html' %}
		
	<h1>Сведения о компании</h1>
	<h2>"Интеллектуальные информационные системы"</h2>
	<h3>Это шаблон из файла templates/blog/about.html</h3>
	<a href="{% url 'blog:home'%}">Home</a>		
	</div>
	{% endblock content %}	

blog/templates/blog/base.html
<!doctype html>
{% load static %}

<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link rel="stylesheet" href="{% static 'blog/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/theme.css' %}">

<!--
	 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
	 <link type="text/css" href="{% static '/blog/css/styles.css' %}" rel="stylesheet"/>
	 --> 
	
	
	 
	{% load django_bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
	
<title>Shuric-WWW</title>
</head>

<body>

    <div class="container p-5 my-3 bg-primary text-white">
		<h1><p class="text-center">Найди себе дело по душе и тебе не придется трудиться ни одного дня в жизни.</p></h1>
	</div>	

<!-- Navbar -->

<div class="container">
	<nav class="navbar navbar-expand-lg bg-body-tertiary">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'main:general' %}">Стартовая страница</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	        <li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Главная</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url "blog:about" %}">Портфолио</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            Варианты размещения
	          </a>
	          <ul class="dropdown-menu">
	            <li><a class="dropdown-item" href="{% url 'blog:single_post' %}">Одиночный пост</a></li>
	            <li><a class="dropdown-item" href="{% url 'blog:left_post' %}">Картинка слева</a></li>
	            <li><a class="dropdown-item" href="{% url 'blog:three_post' %}">Три поста в строке</a></li>
				<li><a class="dropdown-item" href="{% url 'blog:gallery_post' %}">Сетка картинок постов</a></li>
	          </ul>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link disabled">Отключенная</a>
	        </li>
	      </ul>
	      <form class="d-flex" role="search">
	        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
	        <button class="btn btn-outline-success" type="submit">Поиск</button>
	      </form>
	    </div>
	  </div>
	</nav>
</div>
	<!-- Navbar -->


			{% block content %}
			{% endblock content %}
			

		

			{% include "pagination.html" %}


	<script src="{% static 'blog/js/app.js' %}"></script>
    <script src="{% static 'blog/js/theme.js' %}"></script>
</body>
</html>

blog/templates/blog/bootstrap.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">

<!--leftavbar
    <div class="col-sm-3">

      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Активная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Ссылка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Ссылка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Отключенная</a>
        </li>
      </ul>

    </div>
 leftavbar -->

    
        <!--placeholder-->

        <div class="card border-primary mb-3" style="max-width: 1000px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{ post.photo.url }}" class="img-fluid" rounded-start width="300" heigth="300" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content|truncatewords:35 }}</p>
                <p class="card-text"><small class="text-body-secondary">{{ post.created_at }}</small></p>
                <a href="#" class="btn btn-primary">Подробней</a>
              </div>
            </div>
          </div>
        </div>




    </div>
<!-- leftavbar -->

      <!--      -->     
    <div class="col-sm-3">
      
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Активная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Ссылка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Ссылка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Отключенная</a>
        </li>
      </ul>

    </div>
                
  </div>

</div>

<div class="container">
  <div>
    <h1><p class="text-center">Аккордеон
    Создавайте вертикально сворачивающиеся аккордеоны в сочетании с нашим JavaScript-плагином Collapse.</p></h1>
    </div>
    
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Элемент аккордеона #1
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>Это тело аккордеона первого элемента.</strong> Оно отображается по умолчанию, пока плагин свертывания не добавит соответствующие классы, которые мы используем для стилизации каждого элемента. Эти классы управляют общим внешним видом, а также отображением и скрытием с помощью переходов CSS. Вы можете изменить все это с помощью собственного CSS или переопределить наши переменные по умолчанию. Также стоит отметить, что практически любой HTML может быть помещен в <code>.accordion-body</code>, хотя переход ограничивает переполнение.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Элемент аккордеона #2
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>Это тело аккордеона второго элемента.</strong> По умолчанию он скрыт, пока плагин свертывания не добавит соответствующие классы, которые мы используем для стилизации каждого элемента. Эти классы управляют общим внешним видом, а также отображением и скрытием с помощью переходов CSS. Вы можете изменить все это с помощью собственного CSS или переопределить наши переменные по умолчанию. Также стоит отметить, что практически любой HTML может быть помещен в <code>.accordion-body</code>, хотя переход ограничивает переполнение.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Элемент аккордеона #3
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>Это тело аккордеона третьего элемента.</strong> По умолчанию оно скрыто, пока плагин свертывания не добавит соответствующие классы, которые мы используем для стилизации каждого элемента. Эти классы управляют общим внешним видом, а также отображением и скрытием с помощью переходов CSS. Вы можете изменить все это с помощью собственного CSS или переопределить наши переменные по умолчанию. Также стоит отметить, что практически любой HTML может быть помещен в <code>.accordion-body</code>, хотя переход ограничивает переполнение.
          </div>
        </div>
      </div>
    </div>

</div>



{% endblock content %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
	<div class="container">
	
	<h1>Сведения о компании</h1>
	<h2>"Интеллектуальные информационные системы"</h2>
	<h3>Адрес: г. Белогорск, Амурской области ул. Скорикова, д. 22</h3>
	<h3>{{ work }}</h3>
	<h3>Это шаблон из файла templates/blog/contact.html</h3>	
	</div>
	
	{% endblock content %}	

blog/templates/blog/gallery_post.html
{% extends "blog/base.html" %}
{% load blog_tags %}
<!--
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home - Pintereso Bootstrap Template</title>

    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link rel="stylesheet" href="{% static 'blog/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/theme.css' %}">

</head>

<body>
-->
    {% block content %}
    
    <main role="main">
    
        <section class="mt-4 mb-5">
            <div class="container mb-4">
                
                <!--Navbar templates-->
                <div class="row">
                    <!--
                    <nav class="navbar navbar-expand-lg navbar-light bg-white pl-2 pr-2">
                    <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExplore" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarsExplore">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                            <a class="nav-link" href="#">Образ жизни</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Еда</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="{% url "blog:home" %}">Домой</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="#">Путешествовать</a>
                            </li>
                            <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Больше</a>
                            <div class="dropdown-menu shadow-lg" aria-labelledby="dropdown01">
                                <a class="dropdown-item" href="#">Астрономия</a>
                                <a class="dropdown-item" href="#">Природа</a>
                                <a class="dropdown-item" href="#">Приготовление еды</a>
                                <a class="dropdown-item" href="#">Мода</a>
                                <a class="dropdown-item" href="#">Хорошее здоровье</a>
                                <a class="dropdown-item" href="#">Сидение на диете</a>
                            </div>
                            </li>
                        </ul>
                    </div>
                    </nav>
                -->
                </div>
            </div>
                <!--Navbar templates-->
                {% show_categories %}
                <!-- Сетка-->
            <div class="container-fluid">
                <div class="row">
                    <div class="card-columns">
                        {% for post in posts %}     
                        <div class="card card-pin">
                            <img class="card-img" src="{{ post.photo.url }}" alt="Card image">
                            <div class="overlay">
                                <h2 class="card-title title">{{ post.title }}</h2>
                                <div class="more">
                                    <a href="{{ post.get_absolute_url }}">
                                    <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> Читать </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>         
            </div>
                <!--Сетка-->
    
        </section>
    
    </main>   
    
    
    {% endblock content %}

<!--
    <script src="{% static 'blog/js/app.js' %}"></script>
    <script src="{% static 'blog/js/theme.js' %}"></script>
    
    

</body>
-->

blog/templates/blog/left_single_post.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

<div class="container">


<div class="row">

<div class="col-md-3">
    {% include "blog/sidebar.html" %}
</div>

<div
 class="col-md-9">

 <div class="card border-primary mb-3" style="max-width: 1000px;">
    {% for post in posts %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ post.photo.url }}" class="img-fluid" rounded-start width="300" heigth="300" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content|truncatewords:35 }}</p>
                <p class="card-text"><small class="text-body-secondary">{{ post.created_at }}</small></p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Подробней</a>
            </div>
        </div>       
    </div>
    {% endfor %}
</div>

</div>

</div>

    
</div>


  {% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:gallery_post' %}">Навбар</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% for cat in cats %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:category' cat.pk %}">{{ cat.title }}</a>
          </li>        
          {% endfor %}
          

          
        </ul>
        
      </div>
    </div>
  </nav>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}


{% block content %}  
<div class="container">               
	<div class="card text-start">
  		<div class="card-body">
    		<h5 class="card-title">{{ post.title }}</a></h5>
    		{% if post.photo %}
  				<img src="{{ post.photo.url }}" class="mx-auto d-block" width="1000" height="500" alt="...">
  			{% endif %} 
    			<p class="card-text text-start">{{ post.content }}</p>   
  			<div class="card-footer">
    		Дата создания поста: {{ post.created_at }}
  			</div>
  			<a href="{% url 'blog:home' %}" class="btn btn-primary ">На главную</a>
  		</div>
	</div>
</div>
{% endblock content %}


<!--

   <div class="container ">
	{% if post.photo %}
 <img src="{{ post.photo.url }}" class="mx-auto d-block" width="1000" height="500" alt="Cinque Terre"> 
  	{% endif %}
<p><h3>Заголовок: {{ post.title }}</h3></p>
{{ post.content }}
<br>
Дата создания поста: {{ post.created_at }}
<br>
<a  href="{% url 'home' %}" class="btn btn-success">Вернутся на главную</a>
</div>
 -->

blog/templates/blog/sidebar.html
{% load mptt_tags %}
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Категории</h5>
      {% full_tree_for_model blog.Rubric as categories %}
      <p class="card-text">
        <ul>
            {% recursetree categories %}
                <li>
                 <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
                </li>
        
                {% if not node.is_leaf_node %}<ul>{% endif %}

                    {{children}}

                {% if not node.is_leaf_node %}</ul>{% endif %}

            {% endrecursetree %}
        </ul>
      </p>
    </div>
  </div>

main/templates/main/pinlist.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home - Pintereso Bootstrap Template</title>
    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link rel="stylesheet" href="{% static 'main/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/theme.css' %}">

</head>

<body>
<main role="main">
    
    <section class="mt-4 mb-5">
        <div class="container mb-4">
            <h1 class="font-weight-bold title">Исследовать</h1>
            
            <div class="row">
                
                <nav class="navbar navbar-expand-lg navbar-light bg-white pl-2 pr-2">
                <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExplore" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarsExplore">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                        <a class="nav-link" href="#">Образ жизни</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="#">Еда</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url "main:general" %}">Домой</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="#">Путешествовать</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Больше</a>
                        <div class="dropdown-menu shadow-lg" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="#">Астрономия</a>
                            <a class="dropdown-item" href="#">Природа</a>
                            <a class="dropdown-item" href="#">Приготовление еды</a>
                            <a class="dropdown-item" href="#">Мода</a>
                            <a class="dropdown-item" href="#">Хорошее здоровье</a>
                            <a class="dropdown-item" href="#">Сидение на диете</a>
                        </div>
                        </li>
                    </ul>
                </div>
                </nav>
            </div>
        </div>

            <!-- Сетка-->
        <div class="container-fluid">
            <div class="row">
                <div class="card-columns">
                    {% for post in posts %}     
                    <div class="card card-pin">
                        <img class="card-img" src="{{ post.photo.url }}" alt="Card image">
                        <div class="overlay">
                            <h2 class="card-title title">{{ post.title }}</h2>
                            <div class="more">
                                <a href="{{ post.get_absolute_url }}">
                                <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> Читать </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>         
        </div>
            <!--Сетка-->

    </section>

</main>

    <script src="{% static 'main/js/app.js' %}"></script>
    <script src="{% static 'main/js/theme.js' %}"></script>
    

</body>